# Generated by Django 4.2.2 on 2023-06-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]

# shell
# >>> from board.models import Question
# >>> from django.utils import timezone
# >>> q = Question(subject="여름철 실내 적정온도는 얼마인가요?", content='여름철 실내적정온도에 대해서 알고 싶어요.', create_date=timezone.now())
# >>> q.save()
# >>> q.id
# 1
# >>> q.subject
# '여름철 실내 적정온도는 얼마인가요?'
# >>> q.create_date
# datetime.datetime(2023, 6, 19, 5, 37, 10, 414470, tzinfo=datetime.timezone.utc)
